version: "3.9"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: base-app-container
    image: node:20-alpine
    working_dir: /usr/src/base-app
    restart: always
    command: bash -c "npm install --omit=dev && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/base-app
      - HUSKY=0
    volumes:
      - ./dist/:/usr/src/base-app/dist/
      - ./package.json:/usr/src/base-app/package.json
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo
    depends_on:
      - mongo

volumes:
  data:
    driver: local
